import moment from 'moment/moment'

export const getDate = (deadline: number) =>
  moment(deadline)
    .format()
    .substring(4, 16)
    .split('T')
    .join(' ')
    .replace('-01-', ' Jan ')
    .replace('-02-', ' Feb ')
    .replace('-03-', ' Mar ')
    .replace('-04-', ' Apr ')
    .replace('-05-', ' May ')
    .replace('-06-', ' Jun ')
    .replace('-07-', ' Jul ')
    .replace('-08-', ' Aug ')
    .replace('-09-', ' Sep ')
    .replace('-10-', ' Oct ')
    .replace('-11-', ' Nov ')
    .replace('-12-', ' Dec ')
