export const INIT_APP = 'INIT_APP'
export const SET_LOADING = 'SET_LOADING'
export const SET_MOBILE = 'SET_MOBILE'
export const SET_EDITOR = 'SET_EDITOR'
export const SET_ERROR = 'SET_ERROR'

export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const SET_WEEK = 'SET_WEEK'
export const DELETE_WEEK = 'DELETE_WEEK'
export const SUBMIT_WEEK = 'SUBMIT_WEEK'
